config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'application#index'
  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret',
    confirmation: 'verification',
    unlock: 'unblock',
    registration: 'register',
    sign_up: 'cmon_let_me_in'
  }

  resources :users do
    get :dashboard, :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/environment.rb
class Environment < ApplicationRecord
  scope :active, -> { where(active: true) }

  has_many :tasks
end

app/models/task.rb
require 'zip'
class Task < ApplicationRecord
  enum status: %i[new_ paused running done]
  mount_uploader :file, TaskUploader

  belongs_to :user
  belongs_to :environment

  def files
    result = []
    return result unless file_url.present?
    Zip::File.open(file.path) do |zipfile|
      zipfile.each do |entry|
        next unless entry.name.split('.').last == environment&.file_extension
        result << entry.name
      end
    end
    result
  end

  def logs
    begin
      container = ::Docker::Container.get(uid)
    rescue Docker::Error::NotFoundError
      container = nil
    end
    container&.logs(stdout: true)
  end

  validates :file, presence: true, unless: :file_errors_exist?

  private

  def file_errors_exist?
    errors[:attachment].present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, stretches: 12
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'application'

  def index; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    redirect_to task_path(@task), notice: 'Task Is uneditable.' unless @task.new_?
  end

  # POST /tasks
  def create
    @task = Task.new(task_params.merge(user: current_user).merge(uid: SecureRandom.uuid))
    return render :new unless @task.save

    redirect_to edit_task_path(@task), notice: 'Task was successfully created.'
  end

  # PATCH/PUT /tasks/1
  def update
    redirect_to task_path(@task), notice: 'Task Is uneditable.' unless @task.new_?
    if @task.update(task_params)
      ContainerMakers::Python3.call(task: @task)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def task_params
    params.require(:task).permit(:environment_id, :file, :name, :exec_command)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def dashboard; end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <!-- Buefy CSS -->
  <link rel="stylesheet" href="https://unpkg.com/buefy@0.6.6/lib/buefy.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Buefy JavaScript -->
  <script src="https://unpkg.com/buefy"></script>
  <%= javascript_include_tag 'application' %>
  <style>
    body.rtl {
      text-align: right;
    }
    body.rtl form{
      direction: rtl;

    }
    body.rtl input{
      text-align: right;
    }
    .table-wrapper {
       overflow-x: auto;
     }
  </style>
</head>
<body class="<%= 'rtl' if I18n.locale == :fa %>">
  <!-- START NAV -->
  <nav class="navbar">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="../">
          <span class="fa fa-cloud"></span>
        </a>
        <span class="navbar-burger burger" data-target="navbarMenu">
                          <span></span>
                  <span></span>
                  <span></span>
                  </span>
      </div>
      <div id="navbarMenu" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <%= 'حساب کاربری' %>
            </a>
            <% if current_user.present? %>
              <div class="navbar-dropdown">
                <%= link_to Task.model_name.human(count: 2), tasks_path, class: 'navbar-item' %>
                </a>
                <hr class="navbar-divider">
                <%= link_to('خروج', destroy_user_session_path, method: :get, class:'navbar-item') %>
              </div>
            <% else %>
              <div class="navbar-dropdown">
                <%= link_to('ثبت نام', new_user_registration_path,  class:'navbar-item')  %>
                <hr class="navbar-divider">
                <%= link_to('ورود', new_user_session_path, class:'navbar-item')  %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <!-- END NAV -->
  <%= yield %>
  <script>
      Vue.use(Buefy.default)
  </script>
</body>
</html>

app/views/tasks/_form.html.erb
 <%= form_for(@task, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @task.errors.any? %>
    <div class="notification is-danger" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">X</span></button>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: "label"  %>
    <div class="control">
      <%= f.text_field :name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= f.label :environment_id, Task.human_attribute_name('environment'), class: "label"  %>
    <div class="select">
      <%= f.select :environment_id, Environment.active.collect {|e| [ e.name, e.id ] } %>
    </div>
  </div>

  <div class="field">
    <%= f.label :file, Task.human_attribute_name('file'), class: "label"  %>
    <%= link_to Task.human_attribute_name('download_file'), "#{ENV['FILE_SERVER_ADDRESS']}#{@task.file_url}" if @task&.file_url.present? %>
    <i>(<%= "#{t('activerecord.info.task.file')} #{@task&.environment&.name}" %>)</i>
    <div class="control">
      <%= f.file_field :file, class: "input" unless @task&.file_url.present? %>
    </div>
  </div>

  <% if @task&.file_url.present? %>
    <div class="field">
      <%= f.label :exec_command, Task.human_attribute_name('exec_command'), class: "label"  %>
      <div class="select">
        <%= f.select :exec_command, @task.files %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit value: t('d.Save'), class: "button is-link" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="columns">
      <div class="column is-half is-offset-one-quarter">
        <div class="page-header">
          <%= link_to tasks_path, class: 'button is-link' do %>
            <span class="fa fa-list-alt"></span>
          <%= t('d.Back') %>
          <% end %>
          <%= link_to @task, class: 'button is-link' do %>
            <span class="fa fa-info-circle"></span>
          <%= t('d.Show') %>
          <% end %>
          <h1><%= t('d.Editing') %> <%= Task.model_name.human %></h1>
        </div>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/tasks/index.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="columns is-multiline">
      <div class="column is-full">
        <div class="page-header">
          <%= link_to new_task_path, class: 'button is-link' do %>
            <span class="fa fa-plus"></span>
          <%= t('d.New') %> <%= Task.model_name.human %>
          <% end %>
          <h1><%= t('d.Listing') %> <%= Task.model_name.human %></h1>
        </div>
      </div>
      <div class="column is-full table-wrapper">
        <table class="table is-fullwidth">
          <thead>
            <tr>
              <th><%= Task.human_attribute_name('name') %></th>

              <th><%= Task.human_attribute_name('environment') %></th>

              <th><%= Task.human_attribute_name('exec_command') %></th>

              <th><%= t('d.Action') %></th>
            </tr>
          </thead>

          <tbody>
          <%= content_tag_for(:tr, @tasks) do |task| %>
            <td><%= task.name %></td>

            <td><%= task.environment.name %></td>

            <td><%= task.exec_command %></td>

            <td>
              <div class="btn-group">
                <%= link_to  task ,class: "button is-link is-small" do %>
                    <i class="fa fa-eye"></i>
                <% end -%>
                <%= link_to  edit_task_path(task) ,class: "button is-link is-small" do %>
                    <i class="fa fa-edit"></i>
                <% end -%>
                <%= link_to task, method: :delete, data: { confirm: t('s.Suring') } ,class: "button is-link is-small" do %>
                    <i class="fa fa-trash"></i>
                <% end -%>
              </div>
            </td>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/tasks/new.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="columns">
      <div class="column is-half is-offset-one-quarter">
        <div class="page-header">
          <%= link_to tasks_path, class: 'button is-link' do %>
            <span class="fa fa-list-alt"></span>
          <%= t('d.Back') %>
          <% end %>
          <h1><%= t('d.New') %> <%= Task.model_name.human %></h1>
        </div>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/tasks/show.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="columns">
      <div class="column is-half is-offset-one-quarter">
        <div class="page-header">
          <%= link_to tasks_path, class: 'button is-link' do %>
            <span class="fa fa-list-alt"></span>
          <%= t('d.Back') %>
          <% end %>
          <%= link_to edit_task_path(@task), class: 'button is-link' do %>
            <span class="fa fa-pencil"></span>
            <%= t('d.Edit') %>
          <% end %>
          <h1><%= t('d.Show') %> <%= Task.model_name.human %> </h1>
        </div>

        <dl class="dl-horizontal">

          <dt><%= Task.human_attribute_name('name') %>:</dt>
          <dd><%= @task.name %></dd>

          <dt><%= Task.human_attribute_name('environment') %>:</dt>
          <dd><%= @task.environment.name %></dd>

          <dt><%= Task.human_attribute_name('file') %>:</dt>
          <dd><%= link_to Task.human_attribute_name('download_file'), @task.file_url %></dd>

          <dt><%= Task.human_attribute_name('exec_command') %>:</dt>
          <dd><%= @task.exec_command %></dd>

          <dt><%= Task.human_attribute_name('logs') %>:</dt>
          <dd>
            <section class="hero is-black has-text-left	">
              <div class="hero-body">
                <%= simple_format(@task.logs) %>
              </div>
            </section>
          </dd>


        </dl>
      </div>
    </div>
  </div>
</section>

app/views/users/dashboard.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-2">
      <%= link_to tasks_path, class: 'notification box is-primary' do %>
        <%= Task.model_name.human(count: 2) %>
        <span class="fa fa-list"></span>
      <% end %>
    </div>
  </div>
</div>